program dm;

{$R 'dmversion.res' 'dmversion.rc'}
{$R *.dres}
{$I dm.inc}

uses
  {$IFDEF EurekaLog}
  EMemLeaks,
  {$ENDIF EurekaLog}
  Forms,
  Windows,
  fMainForm in 'Source\Main\fMainForm.pas' {fmMainForm},
  fConfig in 'Source\Dialogs\fConfig.pas' {fmConfig},
  fTriggersEditor in 'Source\ProjectForms\fTriggersEditor.pas' {frTriggersEditor: TFrame},
  fScriptViewer in 'Source\Comparer\fScriptViewer.pas' {ScriptViewer},
  LangConst in 'Source\Utils\LangConst.pas',
  fNewProject in 'Source\Dialogs\fNewProject.pas' {fmNewProject},
  fNewRelation in 'Source\Dialogs\fNewRelation.pas' {fmNewRelation},
  uListViewcleaner in 'Source\Utils\uListViewcleaner.pas',
  fGenerateScript in 'Source\Dialogs\fGenerateScript.pas' {fmGenerateScript},
  fdomains in 'Source\Dialogs\fdomains.pas' {fmDomains},
  fSqlEditor in 'Source\Comparer\fSqlEditor.pas' {frSqlEditor: TFrame},
  fDatabaseConvert in 'Source\Dialogs\fDatabaseConvert.pas' {fmDatabaseConvert},
  uDataTypeConversion in 'Source\Model\uDataTypeConversion.pas',
  fProject in 'Source\Main\fProject.pas' {fmProject},
  fTableElements in 'Source\ProjectForms\fTableElements.pas' {fmTableElements: TFrame},
  uProjectExplorer in 'Source\Main\uProjectExplorer.pas',
  uGDAODiagrams in 'Source\Diagram\uGDAODiagrams.pas',
  uTableDiagramBlock in 'Source\Diagram\uTableDiagramBlock.pas',
  uDiagramClass in 'Source\Diagram\uDiagramClass.pas',
  uGDAODragObject in 'Source\Diagram\uGDAODragObject.pas',
  uConfigFrameManager in 'Source\ConfigFrames\uConfigFrameManager.pas',
  fOracleCfg in 'Source\ConfigFrames\fOracleCfg.pas' {frOracleCfg: TFrame},
  fImportProgress in 'Source\ImportWizard\fImportProgress.pas' {frImportProgress: TFrame},
  fImportSave in 'Source\ImportWizard\fImportSave.pas' {frImportSave: TFrame},
  uSystemClass in 'Source\App\uSystemClass.pas',
  fImportPassword in 'Source\ImportWizard\fImportPassword.pas' {frImportPassword: TFrame},
  uAppMetaData in 'Source\App\uAppMetaData.pas',
  fManageVersions in 'Source\Dialogs\fManageVersions.pas' {frmManageVersions},
  fVersionDetails in 'Source\Dialogs\fVersionDetails.pas' {frmVersionDetails},
  fCompareVersion in 'Source\Comparer\fCompareVersion.pas' {Form1},
  fAddVersion in 'Source\Dialogs\fAddVersion.pas' {frmAddVersion},
  dgDBActions in 'Source\Model\dgDBActions.pas',
  uDBConnect in 'Source\Importer\uDBConnect.pas',
  fSQLServer2000Cfg in 'Source\ConfigFrames\fSQLServer2000Cfg.pas' {frSQLServer2000Cfg: TFrame},
  ProjectDBModule in 'Source\Connectors\ProjectDBModule.pas' {DatabaseModule: TDataModule},
  dgBase in 'Source\Model\dgBase.pas',
  fCompareProjects in 'Source\Comparer\fCompareProjects.pas' {frmCompareProjects},
  dDiagramOptions in 'Source\Main\dDiagramOptions.pas' {dmDiagramOptions: TDataModule},
  dgDBTypes in 'Source\Model\dgDBTypes.pas',
  fRelationshipEditor in 'Source\ProjectForms\fRelationshipEditor.pas' {fmRelationshipEditor: TFrame},
  fRelationshipDialog in 'Source\Dialogs\fRelationshipDialog.pas' {fmRelationshipDialog},
  fCompareDictionaries in 'Source\Comparer\fCompareDictionaries.pas' {fmCompareDictionaries},
  uDBProperties in 'Source\Model\uDBProperties.pas',
  uProjectCheck in 'Source\Model\uProjectCheck.pas',
  dMainActions in 'Source\Main\dMainActions.pas' {dmMainActions: TDataModule},
  fMenuRibbon in 'Source\Main\fMenuRibbon.pas' {fmMenuRibbon},
  uDMApp in 'Source\Main\uDMApp.pas',
  fSequenceEditor in 'Source\ProjectForms\fSequenceEditor.pas' {fmSequenceEditor},
  dgCompare in 'Source\Model\dgCompare.pas',
  dgConsts in 'Source\Model\dgConsts.pas',
  dgDBStructurer in 'Source\Model\dgDBStructurer.pas',
  dgMacroDBStructurer in 'Source\Model\dgMacroDBStructurer.pas',
  fImportWizard in 'Source\ImportWizard\fImportWizard.pas' {fmImportWizard},
  uConnectionsFile in 'Source\App\uConnectionsFile.pas',
  fUserConnections in 'Source\Dialogs\fUserConnections.pas' {fmUserConnections},
  fUserConnectionEditor in 'Source\Dialogs\fUserConnectionEditor.pas' {fmUserConnectionEditor},
  uWebUpdate in 'Source\Updater\uWebUpdate.pas',
  fWebUpdate in 'Source\Updater\fWebUpdate.pas' {fmWebUpdateForm},
  fFirebirdCfg in 'Source\ConfigFrames\fFirebirdCfg.pas' {frFirebirdCfg: TFrame},
  fbretrv in 'Source\Importer\fbretrv.pas',
  Aurelius.ExportForm in 'Source\Aurelius\Aurelius.ExportForm.pas' {fmAureliusExport},
  Aurelius.SourceGenerator.Options in 'Source\Aurelius\Aurelius.SourceGenerator.Options.pas',
  Aurelius.SourceGenerator in 'Source\Aurelius\Aurelius.SourceGenerator.pas',
  fDiagramFind in 'Source\Diagram\fDiagramFind.pas' {fmDiagramFind},
  DXInflector in 'Source\Utils\DXInflector.pas',
  uDMTrayIcon in 'Source\Updater\uDMTrayIcon.pas',
  fDuplicateTable in 'Source\Dialogs\fDuplicateTable.pas' {fmDuplicateTable},
  fElevateDBCfg in 'Source\ConfigFrames\fElevateDBCfg.pas' {frElevateDBCfg: TFrame},
  uSQLModule in 'Source\Connectors\uSQLModule.pas',
  dAbsoluteDBModule in 'Source\Connectors\dAbsoluteDBModule.pas',
  dFireDACModule in 'Source\Connectors\dFireDACModule.pas',
  dElevateDBModule in 'Source\Connectors\dElevateDBModule.pas',
  dNexusDBModule in 'Source\Connectors\dNexusDBModule.pas',
  DatabaseTypes.Firebird in 'Source\Model\DatabaseTypes.Firebird.pas',
  DatabaseTypes.PostgreSQL in 'Source\Model\DatabaseTypes.PostgreSQL.pas',
  fMySQLCfg in 'Source\ConfigFrames\fMySQLCfg.pas' {frMySQLCfg: TFrame},
  fPostgreSQLCfg in 'Source\ConfigFrames\fPostgreSQLCfg.pas' {frPostgreSQLCfg: TFrame},
  postgreSQL_retrv in 'Source\Importer\postgreSQL_retrv.pas',
  uDatasetModule in 'Source\Connectors\uDatasetModule.pas',
  Aurelius.SourceGenerator.Options.Xml in 'Source\Aurelius\Aurelius.SourceGenerator.Options.Xml.pas',
  FireDacProjectDBModule in 'Source\Connectors\FireDacProjectDBModule.pas' {dmFireDacProjectDBModule: TDataModule},
  ustrings in 'Source\Utils\ustrings.pas',
  uGDAO in 'Source\Model\uGDAO.pas',
  dgMacroConsts in 'Source\Model\dgMacroConsts.pas',
  atProgress in 'Source\Utils\atProgress.pas',
  atProgressForm in 'Source\Utils\atProgressForm.pas',
  dgGenericDBStructurer in 'Source\Model\dgGenericDBStructurer.pas',
  uSQLMacro in 'Source\Utils\uSQLMacro.pas',
  AbsoluteProjectDBModule in 'Source\Connectors\AbsoluteProjectDBModule.pas',
  NexusProjectDBModule in 'Source\Connectors\NexusProjectDBModule.pas',
  ElevateProjectDBModule in 'Source\Connectors\ElevateProjectDBModule.pas',
  elevateretrv in 'Source\Importer\elevateretrv.pas',
  myretrv in 'Source\Importer\myretrv.pas',
  nexusretrv in 'Source\Importer\nexusretrv.pas',
  AbsoluteRetrv in 'Source\Importer\AbsoluteRetrv.pas',
  sqlanywhere_retrv in 'Source\Importer\sqlanywhere_retrv.pas',
  sqlite_retrv in 'Source\Importer\sqlite_retrv.pas',
  uSQLiteParser in 'Source\Importer\uSQLiteParser.pas',
  oraretrv in 'Source\Importer\oraretrv.pas',
  sqretrv in 'Source\Importer\sqretrv.pas',
  qryretrv in 'Source\Importer\qryretrv.pas',
  DatabaseTypes.SqlAnywhere in 'Source\Model\DatabaseTypes.SqlAnywhere.pas',
  uAppRegistry in 'Source\App\uAppRegistry.pas',
  uAppUtils in 'Source\App\uAppUtils.pas',
  uDatabaseConfigFrames in 'Source\ConfigFrames\uDatabaseConfigFrames.pas',
  fSQLiteCfg in 'Source\ConfigFrames\fSQLiteCfg.pas',
  fNexusDBCfg in 'Source\ConfigFrames\fNexusDBCfg.pas',
  fAbsoluteDBCfg in 'Source\ConfigFrames\fAbsoluteDBCfg.pas',
  fSQLAzureCfg in 'Source\ConfigFrames\fSQLAzureCfg.pas',
  uConsts in 'Source\Utils\uConsts.pas',
  HashUnit in 'Source\Utils\HashUnit.pas',
  Diff in 'Source\Utils\Diff.pas',
  uScripting in 'Source\Utils\uScripting.pas',
  uSQLStyler in 'Source\Utils\uSQLStyler.pas',
  uDialogs in 'Source\Utils\uDialogs.pas',
  dWebUpdate in 'Source\Updater\dWebUpdate.pas',
  uControlUtils in 'Source\Utils\uControlUtils.pas',
  fEditConversionMap in 'Source\Dialogs\fEditConversionMap.pas',
  fConversionMaps in 'Source\Dialogs\fConversionMaps.pas' {fmConversionMaps},
  fEnvironmentSettings in 'Source\Dialogs\fEnvironmentSettings.pas' {fmEnvironmentSettings},
  fObjectEditor in 'Source\ProjectForms\fObjectEditor.pas' {fmObjectEditor: TFrame},
  fMenu in 'Source\Main\fMenu.pas' {fmMenu};

{$R *.RES}

begin
  Application.Initialize;
  Application.MainFormOnTaskBar := True;
  Application.ShowMainForm := false;
  Application.Title := 'TMS Data Modeler';
  Application.CreateForm(TfmMainForm, fmMainForm);
  fmMainForm.InitAll;
  Application.Run;
end.

